### PR TITLE
Add MSAK announcement blog post

### PR DESCRIPTION
**Pull request by robertodauria**
http://website.mlab-sandbox.measurementlab.net/blog/introducing-msak/

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/758)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
A few minor suggestions. :lgtm: - please hold on all reviewers.

> *[Reviewable](https://reviewable.io/reviews/m-lab/website/758#-:-NaIBMwP-En2Dr8mSzqy:b-l35xpk)* status: 0 of 1 approvals obtained (waiting on @KatataK, @laiyi-ohlsen, and @robertodauria)

___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 14 at r2](https://reviewable.io/reviews/m-lab/website/758#-NaIA2Jo-URHYb-3tmCR:-NaIA2Jo-URHYb-3tmCS:b-ex03oy) ([raw file](https://github.com/m-lab/website/blob/adc7af6f0bec74f6e5549629c05b2387d20d20e3/_posts/blog/2023-07-26-introducing-msak.md#L14)):*
> ```Markdown
> Since its inception, M-Lab's flagship **bulk transport capacity** (BTC) measurement protocol, NDT, has always been using a single TCP stream. While this allowed us to get better diagnostic data about the user's connection, over time many have expressed concerns about the ability of the single-stream approach to also effectively fill the link and double as a measurement of **link capacity**. 
> 
> NDT data is also frequently compared to Internet speed test services with a substantially **different server placement model** (usually much closer to the end user, often on the same network as the user's ISP), which makes apples-to-apples comparisons harder. We realized that a multi-stream measurement hosted on the M-Lab platform could provide the missing data to understand the effective impact of multiple streams on throughput measurements and, at the same time, provide a platform to experiment with and shape the next generation of NDT versions.
> ```

The emphasis on "different server placement models" seems to imply a link to some description. I would simply remove the emphasis since you summarize what you mean in parentheses next. 
___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 16 at r2](https://reviewable.io/reviews/m-lab/website/758#-NaI9xbqCM00EYJn8m9c:-NaI9xbqCM00EYJn8m9d:bxx589h) ([raw file](https://github.com/m-lab/website/blob/adc7af6f0bec74f6e5549629c05b2387d20d20e3/_posts/blog/2023-07-26-introducing-msak.md#L16)):*
> ```Markdown
> NDT data is also frequently compared to Internet speed test services with a substantially **different server placement model** (usually much closer to the end user, often on the same network as the user's ISP), which makes apples-to-apples comparisons harder. We realized that a multi-stream measurement hosted on the M-Lab platform could provide the missing data to understand the effective impact of multiple streams on throughput measurements and, at the same time, provide a platform to experiment with and shape the next generation of NDT versions.
> 
> In addition to this, the FCC's **mobile broadband measurement program** explicitly requires that the measurement happens over 3 concurrent streams. By supporting multi-stream measurements, we will be able to fulfill the FCC's requirements.
> ```

Is there a link available to the FCC's mobile broadband measurement program?
___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 28 at r2](https://reviewable.io/reviews/m-lab/website/758#-NaIB0Tb9shPdINCaJKw:-NaIB0Tb9shPdINCaJKx:b7yxat7) ([raw file](https://github.com/m-lab/website/blob/adc7af6f0bec74f6e5549629c05b2387d20d20e3/_posts/blog/2023-07-26-introducing-msak.md#L28)):*
> ```Markdown
> ## Latency testing
> 
> MSAK also provides a client-initiated UDP-based latency testing protocol, which measures latency by sending small UDP packets at a fast rate that is compatible with real-time UDP-based protocols. By running this test, the client will know its latency, jitter, and packet loss.
> ```

s/compatible/comparable/
___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 34 at r2](https://reviewable.io/reviews/m-lab/website/758#-NaIBAozDhseOgoe6PCp:-NaIBAozDhseOgoe6PCq:bed2phl) ([raw file](https://github.com/m-lab/website/blob/adc7af6f0bec74f6e5549629c05b2387d20d20e3/_posts/blog/2023-07-26-introducing-msak.md#L34)):*
> ```Markdown
> ## Summary
> 
> MSAK is under active development, and the best way to stay up-to-date is by following its [official GitHub repository](https://github.com/m-lab/msak). Our first priority is to support Georgia Tech's CellWatch app for mobile measurement. A JavaScript client library for the throughput protocol is planned and will enable us to provide a multi-stream option on [our official speedtest](https://speed.measurementlab.net).
> ```

s/priority/milestone/

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/website/758#-:-NaIBT5P-8qg6GCTi-cV:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @KatataK, @laiyi-ohlsen, and @robertodauria)

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/758)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @KatataK, @laiyi-ohlsen, and @stephen-soltesz)

___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 14 at r2](https://reviewable.io/reviews/m-lab/website/758#-NaIA2Jo-URHYb-3tmCR:-NaMbpxuD5OISd2NoafS:b-896fix) ([raw file](https://github.com/m-lab/website/blob/adc7af6f0bec74f6e5549629c05b2387d20d20e3/_posts/blog/2023-07-26-introducing-msak.md#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The emphasis on "different server placement models" seems to imply a link to some description. I would simply remove the emphasis since you summarize what you mean in parentheses next. 
</blockquote></details>

Done.
___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 16 at r2](https://reviewable.io/reviews/m-lab/website/758#-NaI9xbqCM00EYJn8m9c:-NaMcLhQ3bZTcYVCQ8Uk:b-896fix) ([raw file](https://github.com/m-lab/website/blob/adc7af6f0bec74f6e5549629c05b2387d20d20e3/_posts/blog/2023-07-26-introducing-msak.md#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is there a link available to the FCC's mobile broadband measurement program?
</blockquote></details>

Done.
___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 28 at r2](https://reviewable.io/reviews/m-lab/website/758#-NaIB0Tb9shPdINCaJKw:-NaMcXfw0WYCrc6jfKom:b-896fix) ([raw file](https://github.com/m-lab/website/blob/adc7af6f0bec74f6e5549629c05b2387d20d20e3/_posts/blog/2023-07-26-introducing-msak.md#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/compatible/comparable/
</blockquote></details>

Done.
___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 34 at r2](https://reviewable.io/reviews/m-lab/website/758#-NaIBAozDhseOgoe6PCp:-NaMcdxaBffB2ZkRrfJ8:b-896fix) ([raw file](https://github.com/m-lab/website/blob/adc7af6f0bec74f6e5549629c05b2387d20d20e3/_posts/blog/2023-07-26-introducing-msak.md#L34)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/priority/milestone/
</blockquote></details>

Done.

**Review by laiyi-ohlsen — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/758)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @KatataK, @robertodauria, and @stephen-soltesz)

___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 12 at r5](https://reviewable.io/reviews/m-lab/website/758#-Nar3f-tE0meH_aPRdq5:-Nar3f-tE0meH_aPRdq6:b-g04vl6) ([raw file](https://github.com/m-lab/website/blob/67d41b3eeb217a93f3f4faa6e0274c4dd8b7d9c6/_posts/blog/2023-07-26-introducing-msak.md#L12)):*
> ```Markdown
> ---
> 
> Since its inception, M-Lab's flagship **bulk transport capacity** (BTC) measurement protocol, NDT, has always been using a single TCP stream. While this allowed us to get better diagnostic data about the user's connection, over time many have expressed concerns about the ability of the single-stream approach to also effectively fill the link and double as a measurement of **link capacity**. 
> ```

Suggest: more detailed



_Code quote:_
```Markdown
better
```
___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 14 at r5](https://reviewable.io/reviews/m-lab/website/758#-Nar5Vdw2VdQDL9CrgJt:-Nar5Vdw2VdQDL9CrgJu:bgaiwkx) ([raw file](https://github.com/m-lab/website/blob/67d41b3eeb217a93f3f4faa6e0274c4dd8b7d9c6/_posts/blog/2023-07-26-introducing-msak.md#L14)):*
> ```Markdown
> Since its inception, M-Lab's flagship **bulk transport capacity** (BTC) measurement protocol, NDT, has always been using a single TCP stream. While this allowed us to get better diagnostic data about the user's connection, over time many have expressed concerns about the ability of the single-stream approach to also effectively fill the link and double as a measurement of **link capacity**. 
> 
> NDT data is also frequently compared to Internet speed test services with a substantially different server placement model (usually much closer to the end user, often on the same network as the user's ISP), which makes apples-to-apples comparisons harder. We realized that a multi-stream measurement hosted on the M-Lab platform could provide the missing data to understand the effective impact of multiple streams on throughput measurements and, at the same time, provide a platform to experiment with and shape the next generation of NDT versions.
> ```

s/realized/determined
___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 18 at r5](https://reviewable.io/reviews/m-lab/website/758#-Nar5bYU1PPt4RqltrFn:-Nar5bYU1PPt4RqltrFo:b-n5dnxe) ([raw file](https://github.com/m-lab/website/blob/67d41b3eeb217a93f3f4faa6e0274c4dd8b7d9c6/_posts/blog/2023-07-26-introducing-msak.md#L18)):*
> ```Markdown
> In addition to this, the FCC's **[mobile broadband measurement program](https://www.fcc.gov/general/measuring-mobile-broadband-performance)** explicitly requires that the measurement happens over 3 concurrent streams. By supporting multi-stream measurements, we will be able to fulfill the FCC's requirements.
> 
> What originally started as a "configurable multi-stream ndt7 server" has now evolved into its own M-Lab-hosted experiment: Measurement Swiss-Army Knife, or MSAK.
> ```

Suggest: As a result of these considerations, we are excited to introduce our newest M-Lab hosted experiment: Measurement Swiss-Army Knife, or MSAK.



_Code quote:_
```Markdown
What originally started as a "configurable multi-stream ndt7 server" has now evolved into its own M-Lab-hosted experiment: Measurement Swiss-Army Knife, or MSAK.
```

**Comment by KatataK** [comment]
*[`_posts/blog/2023-07-26-introducing-msak.md` line 12 at r5](https://reviewable.io/reviews/m-lab/website/758#-Nar3f-tE0meH_aPRdq5:-NasOHJ2DuIuNk5BshRH:beiz9hs) ([raw file](https://github.com/m-lab/website/blob/67d41b3eeb217a93f3f4faa6e0274c4dd8b7d9c6/_posts/blog/2023-07-26-introducing-msak.md#L12)):*
<details><summary><i>Previously, laiyi-ohlsen (Lai Yi Ohlsen) wrote…</i></summary><blockquote>

Suggest: more detailed
</blockquote></details>

@laiyi-ohlsen is there any recommendation of information to add?

**Review by stephen-soltesz — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/758#-:-NasT8Lp39N30N0rBPoX:bnfp4nl)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @KatataK and @robertodauria)

___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 12 at r5](https://reviewable.io/reviews/m-lab/website/758#-Nar3f-tE0meH_aPRdq5:-NasSxBV3dLHiqOEY5St:bgzsp0o) ([raw file](https://github.com/m-lab/website/blob/67d41b3eeb217a93f3f4faa6e0274c4dd8b7d9c6/_posts/blog/2023-07-26-introducing-msak.md#L12)):*
<details><summary><i>Previously, KatataK (Katherine Townsend) wrote…</i></summary><blockquote>

@laiyi-ohlsen is there any recommendation of information to add?
</blockquote></details>

Updated in lieu of @robertodauria.
___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 14 at r5](https://reviewable.io/reviews/m-lab/website/758#-Nar5Vdw2VdQDL9CrgJt:-NasT-p8Dk9P50CYEdZm:bgzsp0o) ([raw file](https://github.com/m-lab/website/blob/67d41b3eeb217a93f3f4faa6e0274c4dd8b7d9c6/_posts/blog/2023-07-26-introducing-msak.md#L14)):*
<details><summary><i>Previously, laiyi-ohlsen (Lai Yi Ohlsen) wrote…</i></summary><blockquote>

s/realized/determined
</blockquote></details>

Updated in lieu of @robertodauria.
___
*[`_posts/blog/2023-07-26-introducing-msak.md` line 18 at r5](https://reviewable.io/reviews/m-lab/website/758#-Nar5bYU1PPt4RqltrFn:-NasT3eaEFNOAXzGkIGy:bgzsp0o) ([raw file](https://github.com/m-lab/website/blob/67d41b3eeb217a93f3f4faa6e0274c4dd8b7d9c6/_posts/blog/2023-07-26-introducing-msak.md#L18)):*
<details><summary><i>Previously, laiyi-ohlsen (Lai Yi Ohlsen) wrote…</i></summary><blockquote>

Suggest: As a result of these considerations, we are excited to introduce our newest M-Lab hosted experiment: Measurement Swiss-Army Knife, or MSAK.
</blockquote></details>

Updated in lieu of @robertodauria.

**Pull request merged**
