### PR TITLE
add to the cloud announcement blog post

### PR DESCRIPTION
**Pull request by laiyi-ohlsen**
Once checks pass, previewable here: http://website.mlab-sandbox.measurementlab.net/

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/710)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Thank you!

> *[Reviewable](https://reviewable.io/reviews/m-lab/website/710#-:-N8-o-KTDLF0wybRLJwk:b-9755fn)* status: 0 of 1 approvals obtained (waiting on @laiyi-ohlsen)

___
*[`_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md` line 21 at r1](https://reviewable.io/reviews/m-lab/website/710#-N8-i29K-_Pdgt5EQHnQ:-N8-i29K-_Pdgt5EQHnR:blqbsui) ([raw file](https://github.com/m-lab/website/blob/8de18506238bdcdda8b93044edd4addb5dda11a1/_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md#L21)):*
> ```Markdown
> 
> As of May 2022, M-Lab is proud to announce that we are expanding our infrastructure into the cloud. Our motivations include:
> * **Diversity of measured paths.** As an increasing amount of traffic is served from cloud architecture, including cloud nodes will diversify our representation of a user’s experience. Providing measurements from these pathways will benefit researchers who use our data to derive insights about the quality of user experience, as well as end users who use our tests to better understand the quality of their connection. 
> ```

Alternate phrasing for first point here:

**Measure more Internet paths.** Increasingly, users depend on services hosted in Cloud providers. By including Cloud providers as part of M-Lab's measurement platform, we will measure more paths representative of users' typical experience. Measuring these paths benefits researchers ... 
___
*[`_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md` line 22 at r1](https://reviewable.io/reviews/m-lab/website/710#-N8-hUa50vvu-kofIVsR:-N8-hUa60UgLcf41YpOP:bdjy198) ([raw file](https://github.com/m-lab/website/blob/8de18506238bdcdda8b93044edd4addb5dda11a1/_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md#L22)):*
> ```Markdown
> As of May 2022, M-Lab is proud to announce that we are expanding our infrastructure into the cloud. Our motivations include:
> * **Diversity of measured paths.** As an increasing amount of traffic is served from cloud architecture, including cloud nodes will diversify our representation of a user’s experience. Providing measurements from these pathways will benefit researchers who use our data to derive insights about the quality of user experience, as well as end users who use our tests to better understand the quality of their connection. 
> * **Flexible deployments.** Cloud deployments offer more flexibility and ease when deploying new servers and change the cost/benefit considerations forfactors when considering a new location.
> ```

s/forfactors//
___
*[`_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md` line 31 at r1](https://reviewable.io/reviews/m-lab/website/710#-N8-hXYUDVurweg_dyzz:-N8-hXYUDVurweg_dz--:b-d16kz6) ([raw file](https://github.com/m-lab/website/blob/8de18506238bdcdda8b93044edd4addb5dda11a1/_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md#L31)):*
> ```Markdown
> ## Call for Collaborators
> 
> We are using Google Cloud Platform as an initial test target, due to our team’s familiarity with GCP. However, our next target is test deployments within other cloud providers such as Amazon Web Services and Microsoft Azure. We are seeking partners to support our efforts either monetarily and/or with expertise in these services. [link to separate blog post with more explicit/detailed fundraising call] 
> ```

Does this link exist?

**Review by laiyi-ohlsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/710)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md` line 21 at r1](https://reviewable.io/reviews/m-lab/website/710#-N8-i29K-_Pdgt5EQHnQ:-N8-s4LE-6gKqr1-hQDn:b-896fix) ([raw file](https://github.com/m-lab/website/blob/8de18506238bdcdda8b93044edd4addb5dda11a1/_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md#L21)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Alternate phrasing for first point here:

**Measure more Internet paths.** Increasingly, users depend on services hosted in Cloud providers. By including Cloud providers as part of M-Lab's measurement platform, we will measure more paths representative of users' typical experience. Measuring these paths benefits researchers ... 

</blockquote></details>

Done.
___
*[`_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md` line 22 at r1](https://reviewable.io/reviews/m-lab/website/710#-N8-hUa50vvu-kofIVsR:-N8-s5X05Qa9SmGd_jZc:b-896fix) ([raw file](https://github.com/m-lab/website/blob/8de18506238bdcdda8b93044edd4addb5dda11a1/_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md#L22)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/forfactors//
</blockquote></details>

Done.
___
*[`_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md` line 31 at r1](https://reviewable.io/reviews/m-lab/website/710#-N8-hXYUDVurweg_dyzz:-N8-rw_jEUmQ9eKJxfzS:b-albr1y) ([raw file](https://github.com/m-lab/website/blob/8de18506238bdcdda8b93044edd4addb5dda11a1/_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md#L31)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does this link exist?
</blockquote></details>

No, took out reference

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - w/ one rephrase suggestion.

> *[Reviewable](https://reviewable.io/reviews/m-lab/website/710#-:-N8-tXWI7BdVxqmghzAm:b-lu9l56)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @laiyi-ohlsen and @stephen-soltesz)

___
*[`_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md` line 22 at r1](https://reviewable.io/reviews/m-lab/website/710#-N8-hUa50vvu-kofIVsR:-N8-tdSn6fAEW3ByVgl1:b-mofczu) ([raw file](https://github.com/m-lab/website/blob/8de18506238bdcdda8b93044edd4addb5dda11a1/_posts/blog/2022-07-27-2022-mlab-to-the-cloud.md#L22)):*
<details><summary><i>Previously, laiyi-ohlsen (Lai Yi Ohlsen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we can eliminate the words "for factors"... actually maybe a slight rephrase as "change the cost/benefit considerations for a new location" would eliminate "considerations for ... considering...".

**Comment by stephen-soltesz** [comment]
@laiyi-ohlsen ping

**Pull request merged**
