### PR TITLE
Gardener annotation post

### PR DESCRIPTION
**Pull request by critzo**
This PR adds a blog post discussing the history of annotations, and our current work to move all datatypes to the uuid-annotator and retire the old annotation-service. @stephen-soltesz @robertodauria could you please take a look for accuracy and completeness?

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/647)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/647)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @critzo and @robertodauria)

___
*[_posts/blog/2021-03-11-evolution-of-annotations.md, line 3 at r1](https://reviewable.io/reviews/m-lab/website/647#-MVMhiRH4mhchJ-JGMgL:-MVMhiRH4mhchJ-JGMgM:bkay0cn) ([raw file](https://github.com/m-lab/website/blob/53bbf1c6df2a4091a2d7611703bc1e78bb01d5bf/_posts/blog/2021-03-11-evolution-of-annotations.md#L3)):*
> ```Markdown
> ---
> layout: blog
> title: "Evolution of M-Lab's Data Annotations"
> ```

For this blog post, I recommend qualifying "annotations" as "geographic and network annotations". Within the team we sometimes refer to "annotations" generally as any additional information we end up associating with a raw measurement in BQ. For example, an ndt7 measurement alone does not have any information about geographic or network locations. The uuid-annotator adds those. In the future we hope to include additional "annotations" with information about the switch, service/node versions, traceroutes, etc. That's all for the future and not certain enough to mention here. However, it could be helpful to be specific in this blog post that the annotations we're talking about are specifically geographic and network location metadata.
___
*[_posts/blog/2021-03-11-evolution-of-annotations.md, line 4 at r1](https://reviewable.io/reviews/m-lab/website/647#-MVMiRfr181swx4Hx0CK:-MVMiRfr181swx4Hx0CL:bezlzvd) ([raw file](https://github.com/m-lab/website/blob/53bbf1c6df2a4091a2d7611703bc1e78bb01d5bf/_posts/blog/2021-03-11-evolution-of-annotations.md#L4)):*
> ```Markdown
> layout: blog
> title: "Evolution of M-Lab's Data Annotations"
> author: "Chris Ritzo, Stephen Soltesz"
> ```

Thank you for offering to include me as an author. But, in this case, you've written the entire post. Please take all the credit :)
___
*[_posts/blog/2021-03-11-evolution-of-annotations.md, line 50 at r1](https://reviewable.io/reviews/m-lab/website/647#-MVMj6YG1PIkdZPRuaJL:-MVMj6YG1PIkdZPRuaJM:b-ltof21) ([raw file](https://github.com/m-lab/website/blob/53bbf1c6df2a4091a2d7611703bc1e78bb01d5bf/_posts/blog/2021-03-11-evolution-of-annotations.md#L50)):*
> ```
> premise
> ```

I recommend not using the singular form of this word. "on-premises".
___
*[_posts/blog/2021-03-11-evolution-of-annotations.md, line 114 at r1](https://reviewable.io/reviews/m-lab/website/647#-MVMjsgo0ihQCO3M35NK:-MVMjsgo0ihQCO3M35NL:b-5nqa51) ([raw file](https://github.com/m-lab/website/blob/53bbf1c6df2a4091a2d7611703bc1e78bb01d5bf/_posts/blog/2021-03-11-evolution-of-annotations.md#L114)):*
> ```Markdown
> is reconciling or mapping FIPS-10-4 and ISO 3166-2 subdivision codes, and
> adding support in the [gardener service][gardner] to re-annotate correct ISO
> codes in the ISO standard fields in our schemas. Annotations for our servers is
> ```

"Accurate annotations ... are"
___
*[_posts/blog/2021-03-11-evolution-of-annotations.md, line 126 at r1](https://reviewable.io/reviews/m-lab/website/647#-MVMk4oeD7gUat8NvNik:-MVMk4oeD7gUat8NvNil:b92fxyi) ([raw file](https://github.com/m-lab/website/blob/53bbf1c6df2a4091a2d7611703bc1e78bb01d5bf/_posts/blog/2021-03-11-evolution-of-annotations.md#L126)):*
> ```Markdown
> 
> We hope that this post provides more detail on some items in our roadmap that
> the team is currently working on completing this quarter. As always, if you have
> ```

This work will continue into Q2.

**Comment by critzo** [comment]
___
*[_posts/blog/2021-03-11-evolution-of-annotations.md, line 114 at r1](https://reviewable.io/reviews/m-lab/website/647#-MVMjsgo0ihQCO3M35NK:-MVNGD5o86SlHuItOqRY:bdcqbqz) ([raw file](https://github.com/m-lab/website/blob/53bbf1c6df2a4091a2d7611703bc1e78bb01d5bf/_posts/blog/2021-03-11-evolution-of-annotations.md#L114)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

"Accurate annotations ... are"
</blockquote></details>

ack. thank you.

**Comment by critzo** [comment]
___
*[_posts/blog/2021-03-11-evolution-of-annotations.md, line 50 at r1](https://reviewable.io/reviews/m-lab/website/647#-MVMj6YG1PIkdZPRuaJL:-MVNGH63ByNKZJvf7haA:bf02vef) ([raw file](https://github.com/m-lab/website/blob/53bbf1c6df2a4091a2d7611703bc1e78bb01d5bf/_posts/blog/2021-03-11-evolution-of-annotations.md#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> ```
> premise
> ```

I recommend not using the singular form of this word. "on-premises".
</blockquote></details>

ack. also changed this sentence in general to use plural forms for grammatical consistency

**Comment by critzo** [comment]
___
*[_posts/blog/2021-03-11-evolution-of-annotations.md, line 4 at r1](https://reviewable.io/reviews/m-lab/website/647#-MVMiRfr181swx4Hx0CK:-MVNGTUhE19KoVZaqoEp:b-7lngtu) ([raw file](https://github.com/m-lab/website/blob/53bbf1c6df2a4091a2d7611703bc1e78bb01d5bf/_posts/blog/2021-03-11-evolution-of-annotations.md#L4)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you for offering to include me as an author. But, in this case, you've written the entire post. Please take all the credit :)
</blockquote></details>

ok :)

**Comment by critzo** [comment]
___
*[_posts/blog/2021-03-11-evolution-of-annotations.md, line 3 at r1](https://reviewable.io/reviews/m-lab/website/647#-MVMhiRH4mhchJ-JGMgL:-MVNGW2hCYXHALYYuBK2:b-9vj69j) ([raw file](https://github.com/m-lab/website/blob/53bbf1c6df2a4091a2d7611703bc1e78bb01d5bf/_posts/blog/2021-03-11-evolution-of-annotations.md#L3)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

For this blog post, I recommend qualifying "annotations" as "geographic and network annotations". Within the team we sometimes refer to "annotations" generally as any additional information we end up associating with a raw measurement in BQ. For example, an ndt7 measurement alone does not have any information about geographic or network locations. The uuid-annotator adds those. In the future we hope to include additional "annotations" with information about the switch, service/node versions, traceroutes, etc. That's all for the future and not certain enough to mention here. However, it could be helpful to be specific in this blog post that the annotations we're talking about are specifically geographic and network location metadata.
</blockquote></details>

changed the title and added one additional mention of this distinction in the first paragraph.

**Review by stephen-soltesz — APPROVED** [review]
Cool! :lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/647#-:-MVNI-932sNGu1qSfhQT:b-9lur3b)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria)

**Pull request merged**
