### PR TITLE
update docs, staging deployment branch in .travis.yml

### PR DESCRIPTION
**Pull request by critzo**
This PR updates the Readme and Contributing docs, and corrects the staging deployment branch to `main`.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/679)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/679)* status: 0 of 1 approvals obtained (waiting on @critzo and @laiyi-ohlsen)

___
*[schema_annotationrow.md, line 1 at r1](https://reviewable.io/reviews/m-lab/website/679#-Mvdsnxs6DV35HwG67or:-Mvdsnxs6DV35HwG67os:b-gqxb9n) ([raw file](https://github.com/m-lab/website/blob/587c594d42321844145554e541903a50a6b6c015/schema_annotationrow.md#L1)):*
> ```Markdown
> | Field name       | Type       | Description    |
> ```

Should these files be added outside the `_includes` directory?

**Comment by critzo** [comment]
___
*[schema_annotationrow.md, line 1 at r1](https://reviewable.io/reviews/m-lab/website/679#-Mvdsnxs6DV35HwG67or:-MvdzKnFAvE994rYspU5:bvoxrsk) ([raw file](https://github.com/m-lab/website/blob/587c594d42321844145554e541903a50a6b6c015/schema_annotationrow.md#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should these files be added outside the `_includes` directory?
</blockquote></details>

No, they should be inside it. Will fix.

**Comment by critzo** [comment]
___
*[CONTRIBUTING.md, line 135 at r3](https://reviewable.io/reviews/m-lab/website/679#-Mvev60F4fUNZYUfbANr:-MvezvJF1SlsaoAZUhH1:bb7f2mf) ([raw file](https://github.com/m-lab/website/blob/0884ca44aafbd91a02ed47f331b8e6cd1426ccf1/CONTRIBUTING.md#L135)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This link does not render as intended.
</blockquote></details>

done

**Comment by critzo** [comment]
___
*[CONTRIBUTING.md, line 154 at r3](https://reviewable.io/reviews/m-lab/website/679#-Mvew-Mi26mKmzYTEUbL:-MvezyQ7BSlskiy3jFYI:b-n9tkhd) ([raw file](https://github.com/m-lab/website/blob/0884ca44aafbd91a02ed47f331b8e6cd1426ccf1/CONTRIBUTING.md#L154)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The schema/descriptions are in the `etl` repo, not `etl-schema` (for better or worse).
</blockquote></details>

changed

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/website/679#-:-Mvf-vfb0Muadc0ZCRsl:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
