### PR TITLE
Document unified, extended views; raw tables

### PR DESCRIPTION
**Pull request by critzo**
This PR adds documentation on the ndt unified views, and adds supporting pages presenting strategy for their production, how to use them to create personal custom views for research, and how to transition older queries to use the unified views.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/635)

### CODE REVIEW

**Review by mattmathis — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 2 files at r3, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/635)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @critzo and @stephen-soltesz)

___
*[_pages/tests/ndt/ndt.md, line 161 at r5](https://reviewable.io/reviews/m-lab/website/635#-MTN7Z9OCkQGXA6hn3JL:-MTN7Z9P22lby92GBouh:b-801nyw) ([raw file](https://github.com/m-lab/website/blob/ebccf9a8e004e4d1b7095767aa86e99cdff2bc80/_pages/tests/ndt/ndt.md#L161)):*
> ```Markdown
> Raw tables contain archived raw data parsed and imported into BigQuery. **They
> are provided for pedantic completeness but are no longer recommended for general
> use.**
> ```

@stephen-soltesz I want to call your attention to this section.   The text here somewhat clashes with your preferences, but I wanted to show that this presentation is cleaner for the users.   Note that measurement-lab.ndt_raw is always views, and does not need to be referenced from other views or tables (because they should all reference tables in mlab_oti.base_tables or mlab_oti.ndt_raw).  I think there are multiple acceptable choices for what we do behind scenes, I just want to make the public presentation simple.  
___
*[_pages/tests/ndt/unified-views.md, line 35 at r5](https://reviewable.io/reviews/m-lab/website/635#-MTMHcNV2YF6jhBIBbFf:-MTMHcNV2YF6jhBIBbFg:bfplhuy) ([raw file](https://github.com/m-lab/website/blob/ebccf9a8e004e4d1b7095767aa86e99cdff2bc80/_pages/tests/ndt/unified-views.md#L35)):*
> ```Markdown
> * In BigQuery, Helpful Views are provided in datasets labelled for each
>   experiment.
> * **Helpful views should be the starting point for most people.**
> ```

This  document now feels redundant with the  "NDT Data in BigQuery" section of NDT.md.  Since I prefer longer page, I vote for nuking this entire page.
___
*[_pages/tests/ndt/unified-views-custom.md, line 107 at r5](https://reviewable.io/reviews/m-lab/website/635#-MTNB5CaAdSuKXgKO-Ao:-MTNB5CaAdSuKXgKO-Ap:b-fv0j27) ([raw file](https://github.com/m-lab/website/blob/ebccf9a8e004e4d1b7095767aa86e99cdff2bc80/_pages/tests/ndt/unified-views-custom.md#L107)):*
> ```Markdown
> 	WHERE filter.IsValidBest 
> ),
> SELECT 
> ```

Insert a comment here,  indicating that the rest is one example of a research query using the above custom unified view.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/unified-views.md, line 35 at r5](https://reviewable.io/reviews/m-lab/website/635#-MTMHcNV2YF6jhBIBbFf:-MTNHmFA54I7ZdKioxHi:b8mkdft) ([raw file](https://github.com/m-lab/website/blob/ebccf9a8e004e4d1b7095767aa86e99cdff2bc80/_pages/tests/ndt/unified-views.md#L35)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

This  document now feels redundant with the  "NDT Data in BigQuery" section of NDT.md.  Since I prefer longer page, I vote for nuking this entire page.
</blockquote></details>

agreed. will remove in a subsequent commit.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/unified-views-custom.md, line 107 at r5](https://reviewable.io/reviews/m-lab/website/635#-MTNB5CaAdSuKXgKO-Ao:-MTNITIfCukFdB3_7v04:b2nhysk) ([raw file](https://github.com/m-lab/website/blob/ebccf9a8e004e4d1b7095767aa86e99cdff2bc80/_pages/tests/ndt/unified-views-custom.md#L107)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

Insert a comment here,  indicating that the rest is one example of a research query using the above custom unified view.
</blockquote></details>

ack

**Comment by critzo** [comment]
@mattmathis I've made a commit to address the issues you mentioned.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/635)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @critzo and @mattmathis)

___
*[_pages/tests/ndt/ndt.md, line 57 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTgw3Xi0i5jpCBIwnHJ:-MTgw3Xi0i5jpCBIwnHK:b-fgu113) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L57)):*
> ```
> in in
> ```
___
*[_pages/tests/ndt/ndt.md, line 105 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTqlf1kB8EVEq86kHKZ:-MTqlf1kB8EVEq86kHK_:b-cw31ym) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L105)):*
> ```Markdown
> * Unified views with suffixes resembling date codes are to support differential
>   A/B testing across processing changes (i.e. `unified_downloads_20201026x`).
>   They give researchers a easy way to detect if our canges have any affect on
> ```

type: "canges" -> "changes"
___
*[_pages/tests/ndt/ndt.md, line 129 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTqm19574tAavSz_fQJ:-MTqm19574tAavSz_fQK:b3kmfcz) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L129)):*
> ```Markdown
> added columns describing everything that we know about the data. **The starting
> point for nearly all alternative analysis of M-Lab data should be private,
> custom unified views built on Extended Views.**
> ```

Have you done this with a non-privileged account from a non-M-Lab project? If so, then this could simplify how you've imagined some inter-project workflows operate (meaning we don't need to support anything special). If not, then please confirm this WAI. BQ's view acls might make this more complex than we want.
___
*[_pages/tests/ndt/ndt.md, line 158 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTqn743ALDaJH0-6Sg6:-MTqn743ALDaJH0-6Sg7:bcbfngu) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L158)):*
"pedantic completeness" is the wrong connotation to use to describe these tables for a project dedicated to open data and transparency.

What do you think of:

> They are provided for transparency and completeness by demonstrating a one-to-one correspondence between rows in BQ and files in GCS. Because the unified and extended views are designed for common use cases, these raw tables are not recommended for general use. However, they could be used to validate a low-level bug in the parsing or view logic.
___
*[_pages/tests/ndt/ndt.md, line 170 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTqoTowBiAqI6Itwbqt:-MTqoTowBiAqI6Itwbqu:b1wv0jt) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L170)):*
> ```Markdown
> * Subject to breaking changes
> * In BigQuery, Raw tables are provided in datasets prepended with `raw_`. Tables
>   including `legacy_` in their names were generated by the older parser and are
> ```

I suggest using suffixes instead., i.e. `_legacy`. I'm not entirely sure why we settled on `raw_` prefix b/c this makes the dataset names align randomly and separately alphabetically in the BQ UI.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 57 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTgw3Xi0i5jpCBIwnHJ:-MTr5K1y8kC8d_OXtt6_:b2nhysk) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L57)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> ```
> in in
> ```

</blockquote></details>

ack

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 105 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTqlf1kB8EVEq86kHKZ:-MTr5ZwS1NoYf9dc3_Vj:b-236uth) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L105)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

type: "canges" -> "changes"
</blockquote></details>

acknowleged

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 129 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTqm19574tAavSz_fQJ:-MTr69p6EwdeZUAW1T4C:b5tg2mv) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L129)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Have you done this with a non-privileged account from a non-M-Lab project? If so, then this could simplify how you've imagined some inter-project workflows operate (meaning we don't need to support anything special). If not, then please confirm this WAI. BQ's view acls might make this more complex than we want.
</blockquote></details>

I can confirm that a non-privileged account, only subscribed to Discuss, can access the datasets: aggregate, geographies, intermediate_ndt, library, ndt, raw_ndt, sidestream, and utilization.

I believe what is being proposed is that users who need to make their own custom views can copy the queries or the views themselves into their own project. 
@mattmathis have you tested copying a view from our project to another one?

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 158 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTqn743ALDaJH0-6Sg6:-MTr7ePr2-u53H95218u:b1q56oq) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L158)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

"pedantic completeness" is the wrong connotation to use to describe these tables for a project dedicated to open data and transparency.

What do you think of:

> They are provided for transparency and completeness by demonstrating a one-to-one correspondence between rows in BQ and files in GCS. Because the unified and extended views are designed for common use cases, these raw tables are not recommended for general use. However, they could be used to validate a low-level bug in the parsing or view logic.
</blockquote></details>

I like it. Will change.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 170 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTqoTowBiAqI6Itwbqt:-MTr7koX1ItSxDNeNj14:b-f1y3pm) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L170)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest using suffixes instead., i.e. `_legacy`. I'm not entirely sure why we settled on `raw_` prefix b/c this makes the dataset names align randomly and separately alphabetically in the BQ UI.
</blockquote></details>

I suggest that we discuss this and make this decision together on an upcoming call.

**Comment by critzo** [comment]
@stephen-soltesz @mattmathis My latest commit addresses most of your recent review comments @stephen-soltesz 

There are a couple outstanding items that we could discuss in an upcoming call or reply here.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 161 at r5](https://reviewable.io/reviews/m-lab/website/635#-MTN7Z9OCkQGXA6hn3JL:-MWz10Tt0HQ03GuQtusW:b-896fix) ([raw file](https://github.com/m-lab/website/blob/ebccf9a8e004e4d1b7095767aa86e99cdff2bc80/_pages/tests/ndt/ndt.md#L161)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

@stephen-soltesz I want to call your attention to this section.   The text here somewhat clashes with your preferences, but I wanted to show that this presentation is cleaner for the users.   Note that measurement-lab.ndt_raw is always views, and does not need to be referenced from other views or tables (because they should all reference tables in mlab_oti.base_tables or mlab_oti.ndt_raw).  I think there are multiple acceptable choices for what we do behind scenes, I just want to make the public presentation simple.  
</blockquote></details>

Done.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 170 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTqoTowBiAqI6Itwbqt:-MWz1qedC1zklYWBY1wd:b-896fix) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L170)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

I suggest that we discuss this and make this decision together on an upcoming call. 
</blockquote></details>

Done.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/635)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @critzo, @mattmathis, and @stephen-soltesz)

___
*[.travis.yml, line 14 at r7](https://reviewable.io/reviews/m-lab/website/635#-MWz2Nnt7LbBD8WTD0-L:-MWz2Nnt7LbBD8WTD0-M:b-cwhwr8) ([raw file](https://github.com/m-lab/website/blob/1c4ebc7fdde874aca88a06a6335cc362a85f6a24/.travis.yml#L14)):*
> ```YAML
> - sudo apt-get install -y python3-pip jupyter jupyter-nbconvert
> - sudo -H python3 -m pip install --upgrade setuptools pip
> #- sudo python3 -m pip install jupyter nbconvert
> ```

Delete unused commands.
___
*[_pages/tests/ndt/ndt.md, line 170 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTqoTowBiAqI6Itwbqt:-MWz1z_E7k40FXe-2pDE:b-3mfvxq) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L170)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@mattmathis changes (in a different PR) make `_legacy` a suffix.
___
*[_pages/tests/ndt/unified-views-custom.md, line 1 at r7](https://reviewable.io/reviews/m-lab/website/635#-MWz2X6O6gD-uS7IouSA:-MWz2X6O6gD-uS7IouSB:brcbcth) ([raw file](https://github.com/m-lab/website/blob/1c4ebc7fdde874aca88a06a6335cc362a85f6a24/_pages/tests/ndt/unified-views-custom.md#L1)):*
> ```Markdown
> ---
> ```

I've not reviewed this. I will trust @mattmathis that this works as advertised.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/unified-views-custom.md, line 1 at r7](https://reviewable.io/reviews/m-lab/website/635#-MWz2X6O6gD-uS7IouSA:-MWz2gm76N2nP7vl-jxw:b32wtd) ([raw file](https://github.com/m-lab/website/blob/1c4ebc7fdde874aca88a06a6335cc362a85f6a24/_pages/tests/ndt/unified-views-custom.md#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I've not reviewed this. I will trust @mattmathis that this works as advertised.
</blockquote></details>

ok

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/unified-views.md, line 35 at r5](https://reviewable.io/reviews/m-lab/website/635#-MTMHcNV2YF6jhBIBbFf:-MWz2ye94LnKJto_b30b:b-896fix) ([raw file](https://github.com/m-lab/website/blob/ebccf9a8e004e4d1b7095767aa86e99cdff2bc80/_pages/tests/ndt/unified-views.md#L35)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

agreed. will remove in a subsequent commit.
</blockquote></details>

Done.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/unified-views-custom.md, line 107 at r5](https://reviewable.io/reviews/m-lab/website/635#-MTNB5CaAdSuKXgKO-Ao:-MWz3D5IEG2D29llGqkr:b-896fix) ([raw file](https://github.com/m-lab/website/blob/ebccf9a8e004e4d1b7095767aa86e99cdff2bc80/_pages/tests/ndt/unified-views-custom.md#L107)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

ack
</blockquote></details>

Done.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 170 at r6](https://reviewable.io/reviews/m-lab/website/635#-MTqoTowBiAqI6Itwbqt:-MWz47I23vVX9Yng60dc:b-896fix) ([raw file](https://github.com/m-lab/website/blob/4d791b0042d9a6a201f875fb87804bf6807f8721/_pages/tests/ndt/ndt.md#L170)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

@mattmathis changes (in a different PR) make `_legacy` a suffix.
</blockquote></details>

Done.

**Comment by critzo** [comment]
___
*[.travis.yml, line 14 at r7](https://reviewable.io/reviews/m-lab/website/635#-MWz2Nnt7LbBD8WTD0-L:-MWz49wq6UYB76iO6v6y:b-7tg5pm) ([raw file](https://github.com/m-lab/website/blob/1c4ebc7fdde874aca88a06a6335cc362a85f6a24/.travis.yml#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Delete unused commands.
</blockquote></details>

ack.

**Comment by critzo** [comment]
@stephen-soltesz @mattmathis This PR is now ready for your final review.

**Review by stephen-soltesz — APPROVED** [review]
> Reviewed 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/635)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @mattmathis and @stephen-soltesz)

**Pull request merged**
