### PR TITLE
Add Global Pilot Entry blogpost

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/498)

### CODE REVIEW

**Comment by critzo** [comment]
___
*[_posts/blog/2019-07-30-global-pilot-entry.md, line 38 at r1](https://reviewable.io/reviews/m-lab/website/498#-Ll3Inuv3agesK7jGnS7:-Ll3Inuy-ypELTt-kQ5w:b-2h8dnx) ([raw file](https://github.com/m-lab/website/blob/719e64de74c2505e469131dbe842aa13c7748552/_posts/blog/2019-07-30-global-pilot-entry.md#L38)):*
> ```Markdown
> more sites in Mumbai, and Amsterdam. From these trials, we’ve found that
> performance matches or exceeds the current software stack, and success
> frequence for NDT clients has improved for browser-based clients while
> ```

minor spelling issue: `s/frequence/frequency/`

**Comment by critzo** [comment]
@stephen-soltesz LGTM with one minor comment. Thanks!

**Comment by stephen-soltesz** [comment]
@critzo thank you!

**Comment by stephen-soltesz** [comment]
Part of https://github.com/m-lab/dev-tracker/issues/392

**Pull request merged**
