### PR TITLE
add updated ndt-server post

### PR DESCRIPTION
**Pull request by critzo**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/681)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/681)* status: 0 of 1 approvals obtained (waiting on @critzo and @laiyi-ohlsen)

___
*[_posts/blog/2022-02-16-run-a-private-ndt-server.md, line 274 at r1](https://reviewable.io/reviews/m-lab/website/681#-Mw2XFxwDNEkVblZMC-_:-Mw2XFxwDNEkVblZMC-a:b-h4olmh) ([raw file](https://github.com/m-lab/website/blob/508647b38beb6ea96ed0bca753255f9393020b7f/_posts/blog/2022-02-16-run-a-private-ndt-server.md#L274)):*
> ```Markdown
> 
> ```~bash
> docker run -d --restart=always       \
> ```

This looks incomplete.

**Comment by critzo** [comment]
___
*[_posts/blog/2022-02-16-run-a-private-ndt-server.md, line 274 at r1](https://reviewable.io/reviews/m-lab/website/681#-Mw2XFxwDNEkVblZMC-_:-Mw3XD-rA-O5SsjyqTLv:b2t00a8) ([raw file](https://github.com/m-lab/website/blob/508647b38beb6ea96ed0bca753255f9393020b7f/_posts/blog/2022-02-16-run-a-private-ndt-server.md#L274)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This looks incomplete.
</blockquote></details>

It is incomplete as indicated by the ... on the line below it. It's just to show the --restart flag. Maybe this block of code isn't really necessary.

**Comment by critzo** [comment]
___
*[_posts/blog/2022-02-16-run-a-private-ndt-server.md, line 173 at r1](https://reviewable.io/reviews/m-lab/website/681#-Mw281yn7quS4aT9CuMO:-Mw3Xgz1E2zlw6uJZTf9:b-f9hcgq) ([raw file](https://github.com/m-lab/website/blob/508647b38beb6ea96ed0bca753255f9393020b7f/_posts/blog/2022-02-16-run-a-private-ndt-server.md#L173)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

You might point interested users at https://github.com/m-lab/tcp-info/tree/master/cmd/csvtool to extract some of the data in the JSON.
</blockquote></details>

Can you extract the jsonl files from the .zst archives with csvtool? I hesitate to mention a bunch of tools since people have such wide personal preferences.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/681)* status: 0 of 1 approvals obtained (waiting on @critzo and @laiyi-ohlsen)

___
*[_posts/blog/2022-02-16-run-a-private-ndt-server.md, line 173 at r1](https://reviewable.io/reviews/m-lab/website/681#-Mw281yn7quS4aT9CuMO:-Mw3rpyr562_IXHgARwT:bv7ogx7) ([raw file](https://github.com/m-lab/website/blob/508647b38beb6ea96ed0bca753255f9393020b7f/_posts/blog/2022-02-16-run-a-private-ndt-server.md#L173)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

Can you extract the jsonl files from the .zst archives with csvtool? I hesitate to mention a bunch of tools since people have such wide personal preferences.
</blockquote></details>

The uncompressed JSON is still effectively unusable. The csvtool provides a dump of the raw data. If a specific example here is too much, you could leave these commands out and/or simply refer the reader to the tcp-info csvtool README for more information.

This is a sample command to decompress a zst file and dump the content.
```
go get github.com/m-lab/tcp-info/cmd/csvtool 
docker run -v $PWD:/data --rm --entrypoint /bin/zstd -it measurementlab/tcp-info:v1.5.3 -cd /data/mlab1-pdx0t_1642181106_000000000000B0C6.00045.jsonl.zst | ~/bin/csvtool
```
___
*[_posts/blog/2022-02-16-run-a-private-ndt-server.md, line 274 at r1](https://reviewable.io/reviews/m-lab/website/681#-Mw2XFxwDNEkVblZMC-_:-Mw3pWvG4IsdnY-hmMrm:b-lbwrcy) ([raw file](https://github.com/m-lab/website/blob/508647b38beb6ea96ed0bca753255f9393020b7f/_posts/blog/2022-02-16-run-a-private-ndt-server.md#L274)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

It is incomplete as indicated by the ... on the line below it. It's just to show the --restart flag. Maybe this block of code isn't really necessary. 
</blockquote></details>

ah, okay -- yeah, I would remove this bit and just reference the "Docker command above" in the second bullet above.

**Comment by critzo** [comment]
___
*[_posts/blog/2022-02-16-run-a-private-ndt-server.md, line 173 at r1](https://reviewable.io/reviews/m-lab/website/681#-Mw281yn7quS4aT9CuMO:-Mw70O4g2mqmZ2GiZ2m4:b-fddrgi) ([raw file](https://github.com/m-lab/website/blob/508647b38beb6ea96ed0bca753255f9393020b7f/_posts/blog/2022-02-16-run-a-private-ndt-server.md#L173)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The uncompressed JSON is still effectively unusable. The csvtool provides a dump of the raw data. If a specific example here is too much, you could leave these commands out and/or simply refer the reader to the tcp-info csvtool README for more information.

This is a sample command to decompress a zst file and dump the content.
```
go get github.com/m-lab/tcp-info/cmd/csvtool 
docker run -v $PWD:/data --rm --entrypoint /bin/zstd -it measurementlab/tcp-info:v1.5.3 -cd /data/mlab1-pdx0t_1642181106_000000000000B0C6.00045.jsonl.zst | ~/bin/csvtool
```
</blockquote></details>

ack. will include.

**Comment by critzo** [comment]
___
*[_posts/blog/2022-02-16-run-a-private-ndt-server.md, line 274 at r1](https://reviewable.io/reviews/m-lab/website/681#-Mw2XFxwDNEkVblZMC-_:-Mw70c_41ydxIjk7-V_n:b-7rl0jd) ([raw file](https://github.com/m-lab/website/blob/508647b38beb6ea96ed0bca753255f9393020b7f/_posts/blog/2022-02-16-run-a-private-ndt-server.md#L274)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

ah, okay -- yeah, I would remove this bit and just reference the "Docker command above" in the second bullet above.
</blockquote></details>

done.

**Comment by critzo** [comment]
@stephen-soltesz Addressed your comments in my latest commits. PTAL one last time?

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/681)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by critzo** [comment]
Thanks for the review @stephen-soltesz

**Pull request merged**
