### PR TITLE
add blog post & resources

### PR DESCRIPTION
**Pull request by critzo**
This pr adds a new blog post. Previewable on sandbox once Travis build is completed.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/553)

### CODE REVIEW

**Comment by critzo** [comment]
@laiyi-ohlsen @stephen-soltesz 
post is previewable now on sandbox:
http://website.mlab-sandbox.measurementlab.net/blog/covid19-test-rates-increase/

**Comment by critzo** [comment]
___
*[_posts/blog/2020-04-01-covid19-test-rates-increase.md, line 35 at r1](https://reviewable.io/reviews/m-lab/website/553#-M3qIhIoEFDoDuDpYXPU:-M3qSeE714sO95B8Chx1:bnauimt) ([raw file](https://github.com/m-lab/website/blob/7140ffeb6fed19d56b398a5f2854ddfe39f1d103/_posts/blog/2020-04-01-covid19-test-rates-increase.md#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This was my typo: `three protocols: WSS (Secure WebSockets) and PLAIN (TCP)` -- I started describing all of them and removed the WS b/c it wasn't relevant to the analysis.
</blockquote></details>

ack. I'll add an update to this text.

**Comment by critzo** [comment]
@laiyi-ohlsen Updated intro text. ready for your final review.

**Comment by laiyi-ohlsen** [comment]
This is the biggest nit in the world, but can we have "Time Periods" be the same Header level as "Key takeaways"

**Comment by critzo** [comment]
@laiyi-ohlsen there's currently not a header at for Time Periods. Do you want to change:

> For this analysis, we have selected two time periods:

To:

Time Periods for this Analysis

with the same heading level as "Key Takeaways"?

**Comment by laiyi-ohlsen** [comment]
@critzo Doc is updated! 

<h2>Time Periods</h2>
For this analysis, we have selected two time periods:
Recent:
2020-03-05 to 2020-03-26
3 Weeks Earlier: 
2020-02-13 to 2020-03-05

**Comment by critzo** [comment]
@laiyi-ohlsen My last commit adds the Time Periods heading.

**Pull request merged**
