### PR TITLE
update and reorder links to app and web integrations

### PR DESCRIPTION
**Pull request by critzo**
This PR adds links to app and website integrations on the data/tools page. 
Previewable: http://website.mlab-sandbox.measurementlab.net/data/tools/

@georgiamoon could you review?

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/478)

### CODE REVIEW

**Comment by georgiamoon** [comment]
___
*[_pages/datatools.md, line 44 at r1](https://reviewable.io/reviews/m-lab/website/478#-LduBuTK5gR8WaWpPEbT:-LduBuTK5gR8WaWpPEbU:b-7lxbqe) ([raw file](https://github.com/m-lab/website/blob/789c69547ec8d8f36cc9ba510e67eabd5d0b8345/_pages/datatools.md#L44)):*
> ```Markdown
> ### Website Integrations
> 
> * [The Berlin broadband network](https://www.breitband-berlin.de/#speedtest){:target="_blank"}
> ```

I think this is called `Broadband Berlin`

**Comment by georgiamoon** [comment]
___
*[_pages/datatools.md, line 19 at r1](https://reviewable.io/reviews/m-lab/website/478#-LduC2Xb14idmlljMo7K:-LduC2XcCSorRqbk5wMq:b-amfvd4) ([raw file](https://github.com/m-lab/website/blob/789c69547ec8d8f36cc9ba510e67eabd5d0b8345/_pages/datatools.md#L19)):*
> ```Markdown
> * [MeasurementKit](https://measurement-kit.github.io/){:target="_blank"} _MeasurementKit_ is a C++ library supported by M-Lab, supporting integrations outside of the browser. Supported tests include NDT, Neubot, and the OONI test suite.
> * [Murakami](https://github.com/m-lab/murakami) - _Murakami_ is a tool for creating an automatic M-Lab testing platform with as little effort as possible. Once running, Murakami runs an NDT test roughly every twelve hours and stores the results for your analysis.
> * [Telescope](https://github.com/m-lab/telescope){:target="_blank"} - _Telescope_ is a Python framework designed to extract raw measurements from M-Lab to allow the easy production of research.
> ```

Should we include speed.measurementlab.net here?

**Comment by georgiamoon** [comment]
Oh -- what about IPYS Venezuela?

**Comment by critzo** [comment]
Good call. I'll add a note about "Are we missing..."  
On IPYS, the mapping site we did with them was temp. and is now offline.

**Comment by critzo** [comment]
___
*[_pages/datatools.md, line 19 at r1](https://reviewable.io/reviews/m-lab/website/478#-LduC2Xb14idmlljMo7K:-LduN-jQ8_DyiRAEOekF:b7f0j91) ([raw file](https://github.com/m-lab/website/blob/789c69547ec8d8f36cc9ba510e67eabd5d0b8345/_pages/datatools.md#L19)):*
<details><summary><i>Previously, georgiamoon (georgia bullen) wrote…</i></summary><blockquote>

Should we include speed.measurementlab.net here?
</blockquote></details>

Sure.. Will add.

**Comment by critzo** [comment]
___
*[_pages/datatools.md, line 44 at r1](https://reviewable.io/reviews/m-lab/website/478#-LduBuTK5gR8WaWpPEbT:-LduN2AbBzhl3UeSv88R:bbedvki) ([raw file](https://github.com/m-lab/website/blob/789c69547ec8d8f36cc9ba510e67eabd5d0b8345/_pages/datatools.md#L44)):*
<details><summary><i>Previously, georgiamoon (georgia bullen) wrote…</i></summary><blockquote>

I think this is called `Broadband Berlin`
</blockquote></details>

Thanks. Will correct.

**Pull request merged**
