### PR TITLE
add office hours info to learn page

### PR DESCRIPTION
**Pull request by laiyi-ohlsen**
Adds office hours to learn page of the website: http://website.mlab-sandbox.measurementlab.net/learn/

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/755)

### CODE REVIEW

**Comment by KatataK** [comment]
Looks great only should we pitch people to the FAQ page rather than support? Former is more user friendly but maybe there's still plans to merge.

**Comment by laiyi-ohlsen** [comment]
@KatataK Oo good catch, updated link to FAQ page.

**Comment by KatataK** [comment]
I see that in the code but it's not reflecting in sandbox? not sure why that is.

**Comment by laiyi-ohlsen** [comment]
Sometimes I have to clear cache to see the update 🤷‍♀️

**Comment by KatataK** [comment]
Not my precious cache... Yeah you're so right that did it. Thank you! LGTM

**Pull request merged**
