### PR TITLE
Sandbox document unified views mm1

### PR DESCRIPTION
**Pull request by mattmathis**
Incremental test: update dataset ndt_intermediate

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/646)

### CODE REVIEW

**Comment by critzo** [comment]
@mattmathis @stephen-soltesz This PR is ready for your final review.

**Review by mattmathis — COMMENTED** [review]
Several nits, but no serious problems.    Nest steps:
 - nits
 - email to discuss about the table name change
 - (short delay) push this and https://github.com/m-lab/etl-schema/pull/96
 - (longer delay) manually remove old views

> *[Reviewable](https://reviewable.io/reviews/m-lab/website/646#-:-MX-Ju6Q9-BIG4qtWxxr:b-nayl45)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[_pages/tests/ndt/ndt.md, line 58 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-Gj2m3glRJcIzcX0c:-MX-Gj2m3glRJcIzcX0d:b-dcx9gn) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/ndt.md#L58)):*
> ```Markdown
> All of the raw data and log files from the measurement fleet are archived in
> their original format and available in Google Cloud Storage:
> https://console.cloud.google.com/storage/browser/archive-measurement-lab/ndt](https://console.cloud.google.com/storage/browser/archive-measurement-lab/ndt){:target="_blank"}.
> ```

markdown bleeding into formatted page 
___
*[_pages/tests/ndt/ndt.md, line 130 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-GGogDWkERH5ZUIWL:-MX-Flrs2c4BZRZ4Zf5L:b4yo2r4) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/ndt.md#L130)):*
> ```
> * [Evolution of NDT]({{ site.baseurl }}/blog/evolution-of-ndt/)
> * [Introducing ndt7](v/blog/ndt7-introduction/)
> ```
I get a 404 on Introducing NDT
___
*[_pages/tests/ndt/ndt.md, line 142 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-BODFDAkfGJeE9hn7:-MX-BODFDAkfGJeE9hn8:b-qnvp06) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/ndt.md#L142)):*
> ```Markdown
>   * [Future] joined with traceroute and other data sets such as platform load telemetry and Internet health indicators
>   * Schemas are supersets of the unified view schema and raw tables schemas; They differs per tool and raw parser version
>   * Designed to support user implemented Custom Universal Views @@@@ links to instructions and examples
> ```

Add link, remove @@@@
___
*[_pages/tests/ndt/ndt.md, line 172 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-GOnt89aBWmYUM1k2:-MX-GOnuAGNeo5qj9n3n:bayhgjn) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/ndt.md#L172)):*
> ```Markdown
>     * measurement-lab.ndt_raw.tcpinfo - [tcp-info description and schema]({{ site.basurl }}/tests/tcp-info)
>     * measurement-lab.ndt_raw.traceroute - [traceroute description and schema]({{ site.basurl }}/tests/traceroute)
>     * measurement-lab.ndt_raw.annotation - [annotation description and schema]({{ site.basurl }}/tests/annotations)
> ```

404 error on annotation description and schema
___
*[_pages/tests/ndt/unified-views-custom.md, line 83 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-I4gkAq7nXHIy-gQo:-MX-I4glB-6HBT8z_Mot:bfptwj9) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/unified-views-custom.md#L83)):*
> ```Markdown
> 	FROM (
> 
>     -- 2020-03-12 to present
> ```

text alignment
___
*[_pages/tests/ndt/unified-views-custom.md, line 120 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-I_Vd6jo3IF_HqTLK:-MX-I_Vd6jo3IF_HqTLL:b-gx30h1) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/unified-views-custom.md#L120)):*
> ```Markdown
> ```
> 
> Graph displaying WSCALE by year
> ```

I don't see the image.

**Comment by critzo** [comment]
@mattmathis Latest commit addresses your review items. Could you PTAL when Travis build is completed?

**Review by mattmathis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/646)* status: 0 of 1 approvals obtained

*[a discussion](https://reviewable.io/reviews/m-lab/website/646#-MX47oCM5sqtbc0Wd9aC:-MX47oCM5sqtbc0Wd9aD:bhkz7ul) (no related file):*
LGTM - on nit, one broken link.  I don't consider either to be blocking.

---
___
*[_pages/tests/ndt/ndt.md, line 88 at r7](https://reviewable.io/reviews/m-lab/website/646#-MX46n1M4s6g9OKxQlnb:-MX46n1M4s6g9OKxQlnc:bg2vjfm) ([raw file](https://github.com/m-lab/website/blob/1cae5036398f58dfd2ba627f6aa6a858e4e64b69/_pages/tests/ndt/ndt.md#L88)):*
> ```Markdown
> views, please see the links below:
> 
> * [How NDT Views Are Derived and Published][ndt-views]
> ```

New 404 error on ndt-views ?
___
*[_pages/tests/ndt/ndt.md, line 121 at r7](https://reviewable.io/reviews/m-lab/website/646#-MX47QjDCJmI1OdgcUH6:-MX47QjDCJmI1OdgcUH7:bw5vq2) ([raw file](https://github.com/m-lab/website/blob/1cae5036398f58dfd2ba627f6aa6a858e4e64b69/_pages/tests/ndt/ndt.md#L121)):*
> ```Markdown
> * Unified views with suffixes resembling date codes are to support differential
>   A/B testing across processing changes. They give researchers a easy way to
>   detect if our canges have any affect on downstream research results.
> ```

canges (sp)

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/646)* status: 0 of 1 approvals obtained (waiting on @mattmathis)

___
*[_pages/tests/ndt/ndt.md, line 168 at r7](https://reviewable.io/reviews/m-lab/website/646#-MX7s1tmEg44khHH1989:-MX7s1tmEg44khHH198A:bw51dpc) ([raw file](https://github.com/m-lab/website/blob/1cae5036398f58dfd2ba627f6aa6a858e4e64b69/_pages/tests/ndt/ndt.md#L168)):*
> ```Markdown
>     * measurement-lab.ndt_raw.ndt7 - [ndt7 description and schema]({{ site.baseurl }}/tests/ndt/ndt7/#ndt7-bigquery-schema)
>     * measurement-lab.ndt_raw.legacy_ndt5 - [ndt5 description and schema]({{ site.baseurl }}/tests/ndt/ndt5/#ndt5-bigquery-schema)
>     * measurement-lab.ndt_raw.legacy_web100 - [web100 description and schema]({{ site.baseurl }}/tests/ndt/web100/)
> ```

Please preserve `_legacy` as a suffix for these view names.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
A few more comments after a thorough read through. After those edits this will lgtm.

> *[Reviewable](https://reviewable.io/reviews/m-lab/website/646#-:-MX8ajOw50av1uNPimWz:b-j0hni7)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @mattmathis)

___
*[_pages/tests/ndt/ndt.md, line 147 at r8](https://reviewable.io/reviews/m-lab/website/646#-MX8Xxj36vPs-WRJj9oD:-MX8Xxj43YAefi_ZxWSs:b-fj3zjb) ([raw file](https://github.com/m-lab/website/blob/35fd9261822d5cfba920d1902c9624fafc8fc380/_pages/tests/ndt/ndt.md#L147)):*
> ```Markdown
>     * measurement-lab.ndt_intermediate.extended_web100_downloads
>     * measurement-lab.ndt_intermediate.extended_web100_uploads
>   * **The starting point for nearly all alternative analysis of M-Lab data should be private custom unified views built on Extended Views**
> ```

nit: Remove "private" -- this is an unnecessary qualifier. "custom unified views" is consistent with the page title used below.
___
*[_pages/tests/ndt/ndt.md, line 154 at r8](https://reviewable.io/reviews/m-lab/website/646#-MX8Y8dt-JYFXHfkz2GP:-MX8Y8dt-JYFXHfkz2GQ:b-reizly) ([raw file](https://github.com/m-lab/website/blob/35fd9261822d5cfba920d1902c9624fafc8fc380/_pages/tests/ndt/ndt.md#L154)):*
> ```Markdown
> ## Raw Tables
>   * The archived raw data parsed and imported into BigQuery
>   * **They are provided for pedantic completeness but are no longer recommended for general use**
> ```

*Do not use 'pedantic' to describe the raw tables.* This has obvious negative connotations and there are positive reasons for our publishing the raw tables. I've provided more helpful text in other PRs. Please use something similar to that here.
___
*[_pages/tests/ndt/unified-views-migrate.md, line 40 at r8](https://reviewable.io/reviews/m-lab/website/646#-MX8a6WVByBo64MLf680:-MX8a6WVByBo64MLf681:b-186ohe) ([raw file](https://github.com/m-lab/website/blob/35fd9261822d5cfba920d1902c9624fafc8fc380/_pages/tests/ndt/unified-views-migrate.md#L40)):*
> ```Markdown
> ## NDT Views Reference
> 
> We now publish three series of BigQuery Views for NDT data: "Raw", "Extended"
> ```

We will also publish the "Joined" or "Materialized" tables.

Alphabetically, this will naturally order them as:

* ndt.*
* ndt_intermediate.*
* ndt_materialized.*
* ndt_raw.*

Which is a happy accident, mirroring the processing stages of the ETL pipeline.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 58 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-Gj2m3glRJcIzcX0c:-MXCqkKE4iKq_SHLs16y:bgo06m3) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/ndt.md#L58)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

markdown bleeding into formatted page 
</blockquote></details>

resolved in latest commits

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 88 at r7](https://reviewable.io/reviews/m-lab/website/646#-MX46n1M4s6g9OKxQlnb:-MXCqz-621CChYPCyU1Y:ba1fes8) ([raw file](https://github.com/m-lab/website/blob/1cae5036398f58dfd2ba627f6aa6a858e4e64b69/_pages/tests/ndt/ndt.md#L88)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

New 404 error on ndt-views ?
</blockquote></details>

link was to the page we decided to remove. deleted in latest commit.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 121 at r7](https://reviewable.io/reviews/m-lab/website/646#-MX47QjDCJmI1OdgcUH6:-MXCr6FFBQF6ymOjHuwE:b-kz468k) ([raw file](https://github.com/m-lab/website/blob/1cae5036398f58dfd2ba627f6aa6a858e4e64b69/_pages/tests/ndt/ndt.md#L121)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

canges (sp)
</blockquote></details>

corrected in last commit.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 130 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-GGogDWkERH5ZUIWL:-MXCrAJ982s0kEzTGEzq:b-bpuvcy) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/ndt.md#L130)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

> ```
> * [Evolution of NDT]({{ site.baseurl }}/blog/evolution-of-ndt/)
> * [Introducing ndt7](v/blog/ndt7-introduction/)
> ```
I get a 404 on Introducing NDT
</blockquote></details>

corrected link in last commit.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 142 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-BODFDAkfGJeE9hn7:-MXCrDrv8xIXJI-wio7q:bb7f2mf) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/ndt.md#L142)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

Add link, remove @@@@
</blockquote></details>

done

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 154 at r8](https://reviewable.io/reviews/m-lab/website/646#-MX8Y8dt-JYFXHfkz2GP:-MXCrYEi-1SvGkCauvjh:b2383ig) ([raw file](https://github.com/m-lab/website/blob/35fd9261822d5cfba920d1902c9624fafc8fc380/_pages/tests/ndt/ndt.md#L154)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

*Do not use 'pedantic' to describe the raw tables.* This has obvious negative connotations and there are positive reasons for our publishing the raw tables. I've provided more helpful text in other PRs. Please use something similar to that here.
</blockquote></details>

I completely agree. Just noting that this text is residual from the several PRs opened earlier that had major merge conflicts. Will correct as we discussed previously.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 172 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-GOnt89aBWmYUM1k2:-MXCrqJf14W3nXv3ehY4:b-b40501) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/ndt.md#L172)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

404 error on annotation description and schema
</blockquote></details>

Removed link for now and will add later once the views are actually published.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/unified-views-custom.md, line 83 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-I4gkAq7nXHIy-gQo:-MXCst8C2paJJvK5WvwZ:b1vh3ab) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/unified-views-custom.md#L83)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

text alignment
</blockquote></details>

will be corrected in upcoming commit.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/unified-views-custom.md, line 120 at r6](https://reviewable.io/reviews/m-lab/website/646#-MX-I_Vd6jo3IF_HqTLK:-MXCsxRG4Gc1o5frzHQO:b-5sz06r) ([raw file](https://github.com/m-lab/website/blob/ad75950e85ef1aeefe6e0cc96d7e44976be26ab5/_pages/tests/ndt/unified-views-custom.md#L120)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

I don't see the image.
</blockquote></details>

corrected in previous commit.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/unified-views-migrate.md, line 40 at r8](https://reviewable.io/reviews/m-lab/website/646#-MX8a6WVByBo64MLf680:-MXCt30d39Q7YhDB3nV-:b-nt9eef) ([raw file](https://github.com/m-lab/website/blob/35fd9261822d5cfba920d1902c9624fafc8fc380/_pages/tests/ndt/unified-views-migrate.md#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We will also publish the "Joined" or "Materialized" tables.

Alphabetically, this will naturally order them as:

* ndt.*
* ndt_intermediate.*
* ndt_materialized.*
* ndt_raw.*

Which is a happy accident, mirroring the processing stages of the ETL pipeline.
</blockquote></details>

This is the first mention of ndt_materialized.* in this PR. @mattmathis should these four datasets describing the various views also be mirrored on the ndt page and/or the ndt-custom-views page?

**Comment by critzo** [comment]
Thank you @stephen-soltesz . Reviewed with comments- one in particular for @mattmathis re: "materialized" views in the ndt_materialized dataset. PTAL?

**Comment by critzo** [comment]
*[a discussion](https://reviewable.io/reviews/m-lab/website/646#-MX47oCM5sqtbc0Wd9aC:-MXCtq-_7cgpJLUfDJLS:b-nv9448) (no related file):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

LGTM - on nit, one broken link.  I don't consider either to be blocking.
</blockquote></details>

@mattmathis please review comment re: ndt_materialized - all other comments are either addressed or will be in an upcoming commit.

---

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/unified-views-migrate.md, line 40 at r8](https://reviewable.io/reviews/m-lab/website/646#-MX8a6WVByBo64MLf680:-MXCuN_704mSsWEqnVIY:b2thkls) ([raw file](https://github.com/m-lab/website/blob/35fd9261822d5cfba920d1902c9624fafc8fc380/_pages/tests/ndt/unified-views-migrate.md#L40)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

This is the first mention of ndt_materialized.* in this PR. @mattmathis should these four datasets describing the various views also be mirrored on the ndt page and/or the ndt-custom-views page? 
</blockquote></details>

Additional comment - @mattmathis has suggested that the documentation should say "Extended" instead of "Intermediate". I am not sure I agree with that since the naming consistency is also a goal here. @mattmathis do you have issue with us using "Intermediate" instead of "Extended" for more clarity?

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/646)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @mattmathis and @stephen-soltesz)

___
*[_pages/tests/ndt/unified-views-migrate.md, line 40 at r8](https://reviewable.io/reviews/m-lab/website/646#-MX8a6WVByBo64MLf680:-MXDJGHU2kA-4j-EmbKd:bb2moow) ([raw file](https://github.com/m-lab/website/blob/35fd9261822d5cfba920d1902c9624fafc8fc380/_pages/tests/ndt/unified-views-migrate.md#L40)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

Additional comment - @mattmathis has suggested that the documentation should say "Extended" instead of "Intermediate". I am not sure I agree with that since the naming consistency is also a goal here. @mattmathis do you have issue with us using "Intermediate" instead of "Extended" for more clarity? 
</blockquote></details>

Discussed with @critzo -- the best reference currently for these plans is in the ETL Foundations doc linked from our roadmap. And, it may not be necessary to document the "materialized" stage yet b/c it doesn't exist, but iiuc, that is the long term direction we're headed where the annotated tables are no longer in `ndt.*` but eventually moved to `ndt_materialized.*` which are referenced by the intermediate and unified views.

**Comment by critzo** [comment]
@stephen-soltesz I've pushed one more commit that addresses our discussion and requested edits. Also this does re-order and format some content for readability, and adds example queries that were missing from previous commits. PTAL when you have a moment?

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/646)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @mattmathis and @stephen-soltesz)

___
*[_pages/tests/ndt/ndt.md, line 96 at r9](https://reviewable.io/reviews/m-lab/website/646#-MXYIxzR98maNAAjvTqg:-MXYIxzR98maNAAjvTqh:bx7xxox) ([raw file](https://github.com/m-lab/website/blob/aaf0c67ff43a5e991f17a1a712827bc4984dbab7/_pages/tests/ndt/ndt.md#L96)):*
> ```Markdown
> |:--------|:------------|
> | `measurement-lab.ndt.*` | [Unified Views](#unified-views) in the `ndt` dataset present a unified schema for all ndt datatypes (web100, ndt5, ndt7), and filter to only provide tests meeting our team's current understanding of completeness & research quality as well as removing rows resulting from M-Lab's operations and monitoring systems. |
> | `measurement-lab.ndt_intermediate.*` | [Extended Views](#extended-views) in the `ndt_intermediate` dataset join raw measurements with annotations, and remap column names across all ndt datatypes (web100, ndt5, ndt7) to provide a common schema for use in the Unified Views. |
> ```

Same question about what guarantees we are making about the stability of these schemas. I recommend that we only claim to support the unified schemas. All others are not guaranteed.
___
*[_pages/tests/ndt/unified-views-migrate.md, line 48 at r9](https://reviewable.io/reviews/m-lab/website/646#-MXYI0Qp7g_ujMGvkjm3:-MXYI0Qp7g_ujMGvkjm4:bye1rt8) ([raw file](https://github.com/m-lab/website/blob/aaf0c67ff43a5e991f17a1a712827bc4984dbab7/_pages/tests/ndt/unified-views-migrate.md#L48)):*
> ```Markdown
> |:--------|:------------|
> | `measurement-lab.ndt.*` | [Unified Views](#unified-views) in the `ndt` dataset present a unified schema for all ndt datatypes (web100, ndt5, ndt7), and filter to only provide tests meeting our team's current understanding of completeness & research quality as well as removing rows resulting from M-Lab's operations and monitoring systems. |
> | `measurement-lab.ndt_intermediate.*` | [Extended Views](#extended-views) in the `ndt_intermediate` dataset join raw measurements with annotations, and remap column names across all ndt datatypes (web100, ndt5, ndt7) to provide a common schema for use in the Unified Views. |
> ```

Do we note somewhere that these schemas are not guaranteed to be stable?

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/ndt.md, line 96 at r9](https://reviewable.io/reviews/m-lab/website/646#-MXYIxzR98maNAAjvTqg:-MXYS6MX2TaIXA2dO5bQ:b-s3rpnj) ([raw file](https://github.com/m-lab/website/blob/aaf0c67ff43a5e991f17a1a712827bc4984dbab7/_pages/tests/ndt/ndt.md#L96)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Same question about what guarantees we are making about the stability of these schemas. I recommend that we only claim to support the unified schemas. All others are not guaranteed.
</blockquote></details>

I will add some text to this effect. My understanding is that the goal is schema stability in the unified views, not for intermediate or otherwise.

**Comment by critzo** [comment]
___
*[_pages/tests/ndt/unified-views-migrate.md, line 48 at r9](https://reviewable.io/reviews/m-lab/website/646#-MXYI0Qp7g_ujMGvkjm3:-MXYTZEGBWXUAnFcaOkY:bsxm0ck) ([raw file](https://github.com/m-lab/website/blob/aaf0c67ff43a5e991f17a1a712827bc4984dbab7/_pages/tests/ndt/unified-views-migrate.md#L48)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do we note somewhere that these schemas are not guaranteed to be stable?
</blockquote></details>

ack. same response. will add.

**Review by critzo — APPROVED** [review]
> Reviewed 1 of 4 files at r5, 1 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/646)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @mattmathis and @stephen-soltesz)

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/website/646#-:-MXYaPHb4P8xpAmyX0Eq:bnfp4nl)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @mattmathis and @stephen-soltesz)

**Pull request merged**
