### PR TITLE
update dependencies in contributing.md; move Neubot to retired status

### PR DESCRIPTION
**Pull request by critzo**
This PR adds some content suggested in #440 and #433, updates the Neubot test status and removes links to resources that NEXA no longer hosts, since Neubot is now decommissioned. @georgiamoon  PTAL?

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/website/453)

### CODE REVIEW

**Comment by georgiamoon** [comment]
So the tricky bit here is that the Neubot client is deprecated, but the server isn't. So I'm not sure we actually want to represent Neubot as retired, since we aren't removing the slice right?

cc @bassosimone

**Comment by critzo** [comment]
> So the tricky bit here is that the Neubot client is deprecated, but the server isn't. So I'm not sure we actually want to represent Neubot as retired, since we aren't removing the slice right?
> 
> cc @bassosimone

I believe the plan is that @bassosimone will apply to host a new test, DASH, on the new Docker-based platform, and that when the platform is migrated, the Neubot server will be retired. Perhaps this PR was premature. I found that the client download links and other URLs from Nexa's site were not resolving, so I took the extra step of anticipating the retirement. @georgiamoon would removing dead links and "retired" language/placement be ok to move this PR forward?

**Comment by critzo** [comment]
@georgiamoon I've changed the Neubot references to indicate only the client has been retired, and that the server will continue to operate on M-Lab until the platform transition. PTAL?

**Comment by critzo** [comment]
Thanks @bassosimone !

**Pull request merged**
